#pragma once

//-----------------------------------------------------------------------------------
//		Purpose	: 
//-----------------------------------------------------------------------------------

enum AvatarStates{

	CHARSTATE_SPAWNING,
	CHARSTATE_DESPAWNING,
	CHARSTATE_STANDING,
	CHARSTATE_SITTING,
	CHARSTATE_FAINTING,
	CHARSTATE_CAMPING,
	CHARSTATE_LEAVING,

	CHARSTATE_MOVING,
	CHARSTATE_DESTMOVE,
	CHARSTATE_FOLLOWING,
	CHARSTATE_FALLING,
	CHARSTATE_DASH_PASSIVE,
	CHARSTATE_TELEPORTING,
	CHARSTATE_SLIDING,
	CHARSTATE_KNOCKDOWN,

	CHARSTATE_FOCUSING,
	CHARSTATE_CASTING,
	CHARSTATE_SKILL_AFFECTING,
	CHARSTATE_KEEPING_EFFECT,
	CHARSTATE_CASTING_ITEM,

	CHARSTATE_STUNNED,
	CHARSTATE_SLEEPING,
	CHARSTATE_PARALYZED,

	CHARSTATE_HTB,
	CHARSTATE_SANDBAG,
	CHARSTATE_CHARGING,
	CHARSTATE_GUARD,

	CHARSTATE_PRIVATESHOP,
	CHARSTATE_DIRECT_PLAY,
	CHARSTATE_OPERATING,
	CHARSTATE_RIDEON,
	CHARSTATE_TURNING,
	CHARSTATE_AIR_JUMP,
	CHARSTATE_AIR_DASH_ACCEL,
	//CHARSTATE_CHASING,			
	//CHARSTATE_STONING,			
	//CHARSTATE_SPRAWLING,			
	//CHARSTATE_FALLING,			
	//CHARSTATE_SWIMMING,			
	//CHARSTATE_RUNNING,			
	//CHARSTATE_WALKING,			
	//CHARSTATE_JUMPING,			
	//CHARSTATE_HOVERING,			
	//CHARSTATE_FLYING,				
	//CHARSTATE_CANDYING,			
	//CHARSTATE_FIGHTING,			

	//CHARSTATE_CRAFTING,			
	//CHARSTATE_LOOTING,			
	//CHARSTATE_TRADING,			
	//CHARSTATE_SHOPPING,			

	CHARSTATE_COUNT,
	INVALID_CHARSTATE = 0xFF

};
