#pragma once
#include "ResultCodes.h"
#include "AvatarStates.h"
#include "ObjectType.h"
#include "ServerStatus.h"
#include "TeleportType.h"
#include "GameRuleType.h"
#include "Races.h"
//-----------------------------------------------------------------------------------
//		Purpose	: 
//-----------------------------------------------------------------------------------

enum Opcode {

	SYS_ALIVE = 1,
	SYS_PING = 2,
	SYS_HANDSHAKE_REQ = 3,
	SYS_HANDSHAKE_RES = 4,
	SYS_HANSAHAKE_NFY = 16,

	/*	***********************************	*/
	/*			User -> Login				*/
	/*	***********************************	*/

	UA_LOGIN_TW_REQ = 103,
	UA_LOGIN_CREATEUSER_REQ = 105,
	UA_LOGIN_DISCONNECT_REQ = 106,

	/*	***********************************	*/
	/*			Login -> User				*/
	/*	***********************************	*/

	AU_HEARTBEAT = 1001,
	AU_LOGIN_RES = 1002,
	AU_LOGIN_CREATEUSER_RES = 1003,
	AU_LOGIN_DISCONNECT_RES = 1004,
	AU_COMMERCIAL_SETTING_NFY = 1005,

	/*	***********************************	*/
	/*			User -> Login				*/
	/*	***********************************	*/

	UC_LOGIN_REQ = 2001,
	UC_CHARACTER_SERVERLIST_REQ = 2002,
	UC_CHARACTER_SERVERLIST_ONE_REQ = 2003,
	UC_CHARACTER_ADD_REQ = 2004,
	UC_CHARACTER_DEL_REQ = 2005,
	UC_CHARACTER_SELECT_REQ = 2006,
	UC_CHARACTER_EXIT_REQ = 2007,
	UC_CHARACTER_LOAD_REQ = 2008,
	UC_CHARACTER_DEL_CANCEL_REQ = 2009,
	UC_CONNECT_WAIT_CHECK_REQ = 2010,
	UC_CONNECT_WAIT_CANCEL_REQ = 2011,
	UC_CHARACTER_RENAME_REQ = 2012,
	UC_CASHITEM_HLSHOP_REFRESH_REQ = 2013,
	UC_CASHITEM_BUY_REQ = 2014,
	UC_CHAR_SERVERLIST_REQ = 2015,

	/*	***********************************	*/
	/*			Character -> User			*/
	/*	***********************************	*/

	CU_HEARTBEAT = 3001,
	CU_SERVER_FARM_INFO = 3002,
	CU_SERVER_CHANNEL_INFO = 3003,
	CU_LOGIN_RES = 3004,
	CU_CHARACTER_SERVERLIST_RES = 3005,
	CU_CHARACTER_SERVERLIST_ONE_RES = 3006,
	CU_CHARACTER_ADD_RES = 3007,
	CU_CHARACTER_DEL_RES = 3008,
	CU_CHARACTER_SELECT_RES = 3009,
	CU_CHARACTER_INFO = 3010,
	CU_CHARACTER_LOAD_RES = 3011,
	CU_CHARACTER_EXIT_RES = 3012,
	CU_CHARACTER_DEL_CANCEL_RES = 3013,
	CU_DISCONNECTED_NFY = 3014,
	CU_SERVER_FARM_INFO_REFRESHED_NFY = 3015,
	CU_SERVER_CHANNEL_INFO_REFRESHED_NFY = 3016,
	CU_CONNECT_WAIT_CHECK_RES = 3017,
	CU_CONNECT_WAIT_COUNT_NFY = 3018,
	CU_CONNECT_WAIT_CANCEL_RES = 3019,
	CU_CONNECT_WAIT_CANCEL_NFY = 3020,
	CU_NETMARBLEMEMBERIP_NFY = 3021,
	CU_CHARACTER_DEL_NFY = 3022,
	CU_CHARACTER_RENAME_RES = 3023,
	CU_CASHITEM_HLSHOP_REFRESH_RES = 3024,
	CU_CASHITEM_BUY_RES = 3025,
	CU_PREMIUM_SLOT_COUNT_NFY = 3026,
	CU_CHAR_SERVERLIST_RES = 3027,
	CU_SERVER_FARM_INFO_NFY = 3028,


	/*	***********************************	*/
	/*			User -> Game				*/
	/*	***********************************	*/

	UG_OPCODE_BEGIN = 4000,

	UG_TUTORIAL_HINT_UPDATE_REQ,
	UG_TUTORIAL_WAIT_CANCEL_REQ,
	UG_TUTORIAL_PLAY_QUIT_REQ,
	UG_CHAR_DASH_KEYBOARD,
	UG_CHAR_DASH_MOUSE,
	UG_CHAR_JUMP,
	UG_CHAR_JUMP_END,
	UG_CHAR_FALLING,
	UG_CHAR_TOGG_SITDOWN,
	UG_CHAR_TOGG_FIGHTING,
	UG_CHAR_ATTACK_BEGIN,
	UG_CHAR_ATTACK_END,
	UG_CHAR_CHARGE,
	UG_CHAR_BLOCK_MODE,
	UG_CHAR_TELEPORT_REQ,
	UG_CHAR_BIND_REQ,
	UG_CHAR_REVIVAL_REQ,
	UG_CHAR_SERVER_CHANGE_REQ,
	UG_CHAR_CHANNEL_CHANGE_REQ,
	UG_CHAR_TARGET_SELECT,
	UG_CHAR_TARGET_INFO,
	UG_CHAR_TARGET_FACING,
	UG_CHAR_READY_FOR_COMMUNITY_SERVER_NFY,
	UG_CHAR_READY_TO_SPAWN,
	UG_CHAR_READY,
	UG_CHAR_MOVE,
	UG_CHAR_DEST_MOVE,
	UG_CHAR_CHANGE_HEADING,
	UG_CHAR_MOVE_COLLISION,
	UG_CHAR_MOVE_COLLISION_END,
	UG_CHAR_STANDING_SLIP,
	UG_CHAR_STANDING_SLIP_END,
	UG_CHAR_LOCATION_SYNC,
	UG_CHAR_AIR_MOVE_SYNC,
	UG_CHAR_CHANGE_DIRECTION_ON_FLOATING,
	UG_CHAR_FOLLOW_MOVE,
	UG_CHAR_FOLLOW_MOVE_SYNC,
	UG_GAME_ENTER_REQ,
	UG_GAME_LEAVE_REQ,
	UG_AUTH_KEY_FOR_COMMUNITY_SERVER_REQ,
	UG_ENTER_WORLD,
	UG_LOADING_COMPLETE_NFY,
	UG_SERVER_COMMAND,
	UG_PING,
	UG_SKILL_TARGET_LIST,
	UG_SKILL_LEARN_REQ,
	UG_SKILL_LEARN_BY_ITEM_REQ,
	UG_SKILL_UPGRADE_REQ,
	UG_SKILL_RP_BONUS_SETTING_REQ,
	UG_HTB_START_REQ,
	UG_HTB_LEARN_REQ,
	UG_HTB_FORWARD_REQ,
	UG_HTB_RP_BALL_USE_REQ,
	UG_BUFF_DROP_REQ,
	UG_ITEM_MOVE_REQ,
	UG_ITEM_MOVE_STACK_REQ,
	UG_ITEM_DELETE_REQ,
	UG_ITEM_EQUIP_REPAIR_REQ,
	UG_ITEM_PICK_REQ,
	UG_ITEM_REPAIR_REQ,
	UG_ITEM_USE_REQ,
	UG_ITEM_UPGRADE_REQ,
	UG_ITEM_IDENTIFY_REQ,
	UG_ZENNY_PICK_REQ,
	UG_SHOP_START_REQ,
	UG_SHOP_BUY_REQ,
	UG_SHOP_SELL_REQ,
	UG_SHOP_END_REQ,
	UG_SHOP_SKILL_BUY_REQ,
	UG_PARTY_CREATE_REQ,
	UG_PARTY_DISBAND_REQ,
	UG_PARTY_INVITE_REQ,
	UG_PARTY_INVITE_CHARID_REQ,
	UG_PARTY_INVITE_CHAR_NAME_REQ,
	UG_PARTY_RESPONSE_INVITATION,
	UG_PARTY_LEAVE_REQ,
	UG_PARTY_KICK_OUT_REQ,
	UG_PARTY_CHANGE_LEADER_REQ,
	UG_PARTY_CHANGE_ZENNY_LOOTING_METHOD_REQ,
	UG_PARTY_CHANGE_ITEM_LOOTING_METHOD_REQ,
	UG_BANK_START_REQ,
	UG_BANK_MOVE_REQ,
	UG_BANK_MOVE_STACK_REQ,
	UG_BANK_END_REQ,
	UG_BANK_ZENNY_REQ,
	UG_BANK_BUY_REQ,
	UG_BANK_ITEM_DELETE_REQ,
	UG_SCOUTER_INDICATOR_REQ,
	UG_SCOUTER_PREDICT_REQ,
	UG_SCOUTER_EQUIP_CHECK_REQ,
	UG_SCOUTER_CHIP_REMOVE_ALL_REQ,
	UG_SCOUTER_ACTIVATION_REQ,
	UG_SOCIAL_ACTION,
	UG_TS_CONFIRM_STEP_REQ,
	UG_TS_CONFIRM_STEP_FOR_USE_ITEM_REQ,
	UG_TS_UPDATE_STATE,
	UG_TS_EXCUTE_TRIGGER_OBJECT,
	UG_QUEST_ITEM_MOVE_REQ,
	UG_QUEST_ITEM_DELETE_REQ,
	UG_QUEST_GIVEUP_REQ,
	UG_QUEST_SHARE,
	UG_QUEST_OBJECT_VISIT_REQ,
	UG_FREEBATTLE_CHALLENGE_REQ,
	UG_FREEBATTLE_ACCEPT_RES,
	UG_QUICK_SLOT_UPDATE_REQ,
	UG_QUICK_SLOT_DEL_REQ,
	UG_PET_DISMISS_PET_REQ,
	UG_TRADE_START_REQ,
	UG_TRADE_OK_RES,
	UG_TRADE_ADD_REQ,
	UG_TRADE_DEL_REQ,
	UG_TRADE_MODIFY_REQ,
	UG_TRADE_ZENNY_UPDATE_REQ,
	UG_TRADE_END_REQ,
	UG_TRADE_CANCEL_REQ,
	UG_TRADE_DENY_REQ,
	UG_GUILD_CREATE_REQ,
	UG_GUILD_INVITE_REQ,
	UG_DRAGONBALL_CHECK_REQ,
	UG_DRAGONBALL_REWARD_REQ,
	UG_TIMEQUEST_ENTER_REQ,
	UG_RANKBATTLE_INFO_REQ,
	UG_RANKBATTLE_JOIN_REQ,
	UG_RANKBATTLE_LEAVE_REQ,
	UG_PORTAL_ADD_REQ,
	UG_PORTAL_REQ,
	UG_PRIVATESHOP_CREATE_REQ,
	UG_PRIVATESHOP_EXIT_REQ,
	UG_PRIVATESHOP_OPEN_REQ,
	UG_PRIVATESHOP_CLOSE_REQ,
	UG_PRIVATESHOP_ITEM_UPDATE_REQ,
	UG_PRIVATESHOP_ITEM_INSERT_REQ,
	UG_PRIVATESHOP_ITEM_GET_REQ,
	UG_PRIVATESHOP_ITEM_DELETE_REQ,
	UG_PRIVATESHOP_ITEM_BUYING_REQ,
	UG_PRIVATESHOP_ENTER_REQ,
	UG_PRIVATESHOP_LEAVE_REQ,
	UG_PRIVATESHOP_ITEM_SELECT_REQ,
	UG_PRIVATESHOP_BUSINESS_REQUEST_REQ,
	UG_PRIVATESHOP_BUSINESS_CONSENT_RES,
	UG_PRIVATESHOP_BUSINESS_WAITTIMEOUT_NFY,
	UG_PRIVATESHOP_BUSINESS_PRICEFLUCTUATIONS_REQ,
	UG_PRIVATESHOP_BUSINESS_IMMEDIATE_ITEM_BUYING_REQ,
	UG_PRIVATESHOP_BUSINESS_CANCEL_REQ,
	UG_MAIL_START_REQ,
	UG_MAIL_SEND_REQ,
	UG_MAIL_READ_REQ,
	UG_MAIL_DEL_REQ,
	UG_MAIL_RETURN_REQ,
	UG_MAIL_RELOAD_REQ,
	UG_MAIL_LOAD_REQ,
	UG_MAIL_ITEM_RECEIVE_REQ,
	UG_MAIL_LOCK_REQ,
	UG_MAIL_MULTI_DEL_REQ,
	UG_WAR_FOG_UPDATE_REQ,
	UG_GUILD_FUNCTION_ADD_REQ,
	UG_GUILD_GIVE_ZENNY,
	UG_GUILD_BANK_START_REQ,
	UG_GUILD_BANK_MOVE_REQ,
	UG_GUILD_BANK_MOVE_STACK_REQ,
	UG_GUILD_BANK_END_REQ,
	UG_GUILD_BANK_ZENNY_REQ,
	UG_GUILD_CREATE_MARK_REQ,
	UG_GUILD_CHANGE_MARK_REQ,
	UG_CROSSFIRE_REQ,
	UG_BANK_LOAD_REQ,
	UG_GUILD_CHANGE_NAME_REQ,
	UG_PARTY_SHARETARGET_REQ,
	UG_RIDE_ON_BUS_REQ,
	UG_RIDE_OFF_BUS_REQ,
	UG_TRANSFORM_CANCEL_REQ,
	UG_SHOP_ITEM_IDENTIFY_REQ,
	UG_DICE_ROLL_REQ,
	UG_BUDOKAI_JOIN_INFO_REQ,
	UG_BUDOKAI_JOIN_STATE_REQ,
	UG_BUDOKAI_MUDOSA_INFO_REQ,
	UG_BUDOKAI_MUDOSA_TELEPORT_REQ,
	UG_BUDOKAI_PARTY_MAKER_REQ,
	UG_BUDOKAI_SOCIAL_ACTION,
	UG_BUDOKAI_PRIZEWINNER_NAME_REQ,
	UG_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_REQ,
	UG_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_REQ,
	UG_BUDOKAI_GM_MATCH_PROGRESS_INFO_REQ,
	UG_BUDOKAI_GM_MATCH_ARENA_ENTER_REQ,
	UG_BUDOKAI_GM_MATCH_ARENA_LEAVE_REQ,
	UG_BUDOKAI_JOIN_TEAM_INFO_REQ,
	UG_BUDOKAI_JOIN_TEAM_REQ,
	UG_BUDOKAI_LEAVE_TEAM_REQ,
	UG_BUDOKAI_LEAVE_TEAM_MEMBER_REQ,
	UG_BUDOKAI_JOIN_INDIVIDUAL_REQ,
	UG_BUDOKAI_LEAVE_INDIVIDUAL_REQ,
	UG_SCOUTER_TURN_ON,
	UG_SCOUTER_TURN_OFF,
	UG_SCOUTER_ITEM_SELL_REQ,
	UG_SHOP_EVENTITEM_START_REQ,
	UG_SHOP_EVENTITEM_BUY_REQ,
	UG_SHOP_EVENTITEM_END_REQ,
	UG_SHOP_GAMBLE_BUY_REQ,
	UG_PARTY_DIFF_CHANGE_REQ,
	UG_PARTY_DUNGEON_INIT_REQ,
	UG_VEHICLE_DIRECT_PLAY_CANCEL_NFY,
	UG_VEHICLE_ENGINE_START_REQ,
	UG_VEHICLE_ENGINE_STOP_REQ,
	UG_VEHICLE_END_REQ,
	UG_VEHICLE_STUNT_NFY,
	UG_VEHICLE_FUEL_REMOVE_NFY,
	UG_SKILL_INIT_REQ,
	UG_SKILL_RESET_PLUS_REQ,
	UG_TELEPORT_CONFIRM_REQ,
	UG_HOIPOIMIX_ITEM_CHECK_REQ,
	UG_HOIPOIMIX_ITEM_MAKE_REQ,
	UG_HOIPOIMIX_ITEM_MAKE_EP_REQ,
	UG_HOIPOIMIX_ITEM_MACHINE_DEL_REQ,
	UG_HOIPOIMIX_JOB_SET_REQ,
	UG_HOIPOIMIX_JOB_RESET_REQ,
	UG_HOIPOIMIX_ITEM_CREATE_EX_REQ,
	UG_ITEM_DISASSEMBLE_REQ,
	UG_CASHITEM_START_REQ,
	UG_CASHITEM_END_REQ,
	UG_CASHITEM_MOVE_REQ,
	UG_CASHITEM_USE_REQ,
	UG_CASHITEM_HLSHOP_START_REQ,
	UG_CASHITEM_HLSHOP_END_REQ,
	UG_CASHITEM_HLSHOP_REFRESH_REQ,
	UG_CASHITEM_BUY_REQ,
	UG_CASHITEM_SEND_GIFT_REQ,
	UG_DOJO_CREATE_REQ,
	UG_DOJO_DELETE_REQ,
	UG_DOJO_FUNCTION_ADD_REQ,
	UG_DOJO_BANK_HISTORY_REQ,
	UG_DOGI_CREATE_REQ,
	UG_DOGI_CHANGE_REQ,
	UG_GUILD_DOGI_CREATE_REQ,
	UG_GUILD_DOGI_CHANGE_REQ,
	UG_DOJO_SCRAMBLE_REQ,
	UG_DOJO_SCRAMBLE_RESPONSE_REQ,
	UG_SHOP_NETPYITEM_START_REQ,
	UG_SHOP_NETPYITEM_BUY_REQ,
	UG_SHOP_NETPYITEM_END_REQ,
	UG_WORLD_MAP_STATUS,
	UG_DOJO_NPC_INFO_REQ,
	UG_GAMEGUARD_AUTH_ANSWER_RES,
	UG_GAMEGUARD_HACK_INFO_NFY,
	UG_SKILL_CASTING_CANCELED_NFY,
	UG_PET_ATTACK_TARGET_NFY,
	UG_DURATION_ITEM_BUY_REQ,
	UG_DURATION_RENEW_REQ,
	UG_BUDOKAI_PRIZEWINNER_TEAM_NAME_REQ,
	UG_GMT_UPDATE_REQ,
	UG_CHAR_LOC_AFTER_KNOCKDOWN_NFY,
	UG_CHAR_LOC_AFTER_SLIDING_NFY,
	UG_CHAR_LOC_AFTER_PUSH_NFY,
	UG_SCS_CHECK_START_RES,
	UG_SCS_CHECK_RES,
	UG_SCS_REPLY_REQ,
	UG_SCS_REMAKE_REQ,
	UG_QUICK_TELEPORT_LOAD_REQ,
	UG_QUICK_TELEPORT_UPDATE_REQ,
	UG_QUICK_TELEPORT_DEL_REQ,
	UG_QUICK_TELEPORT_USE_REQ,
	UG_CHAR_CRESCENT_POPO_REVIVAL_REQ,
	UG_CHARACTER_RENAME_REQ,
	UG_CASHITEM_UPDATE_DURATION_REQ,
	UG_CHAR_DEST_MOVE_SYNC,
	UG_CHAR_NPCSERVER_MOVE_SYNC,
	UG_HOIPOIMIX_ITEM_CREATE_REQ,
	UG_CHAR_EXIT_REQ,
	UG_GAME_EXIT_REQ,
	UG_CHAR_AWAY_REQ,
	UG_CHAR_KEY_UPDATE_REQ,
	UG_CHAR_DIRECT_PLAY_CANCEL,
	UG_CHAR_DIRECT_PLAY_ACK,
	UG_CHAR_KNOCKDOWN_RELEASE_NFY,
	UG_CHAR_SKILL_REQ,
	UG_DRAGONBALL_SCRAMBLE_JOIN_REQ,
	UG_DRAGONBALL_SCRAMBLE_BALL_LOC_REQ,
	UG_CHAR_SKILL_INIT_REQ,
	UG_GUILD_DOGI_DYE_REQ,
	UG_TENKAICHIDAISIJYOU_SELL_REQ,
	UG_TENKAICHIDAISIJYOU_SELL_CANCEL_REQ,
	UG_TENKAICHIDAISIJYOU_BUY_REQ,
	UG_TENKAICHIDAISIJYOU_LIST_REQ,
	UG_MASCOT_SUMMON_REQ,
	UG_MASCOT_UNSUMMON_REQ,
	UG_MASCOT_DELETE_REQ,
	UG_MASCOT_RING_ACTION_REQ,
	UG_MASCOT_RING_REMOVE_ALL_REQ,
	UG_MASCOT_SUMMON_REQ_EX,
	UG_MASCOT_UNSUMMON_REQ_EX,
	UG_MASCOT_DELETE_REQ_EX,
	UG_MASCOT_RING_MATERIAL_DISASSEMBLE_REQ,
	UG_MASCOT_RING_ACTION_END_REQ,
	UG_REMOTE_SHOP_BUY_REQ,
	UG_REMOTE_SHOP_SELL_REQ,
	UG_REMOTE_ITEM_EQUIP_REPAIR_REQ,
	UG_REMOTE_ITEM_REPAIR_REQ,
	UG_REMOTE_SHOP_ITEM_IDENTIFY_REQ,
	UG_WORLD_LAVA_ENTERED_NFY,
	UG_WORLD_LAVA_LEFT_NFY,
	UG_SKILL_ONE_RESET_REQ,
	UG_CASHITEM_INFO_REQ,
	UG_ULTIMATE_DUNGEON_ENTER_REQ,
	UG_PARTY_MATCHING_REGISTER_REQ,
	UG_PARTY_MATCHING_JOIN_REQ,
	UG_PARTY_MATCHING_ROLEPLAY_REQ,
	UG_PARTY_MATCHING_UNREGISTER_REQ,
	UG_PARTY_MATCHING_LIST_REQ,
	UG_PARTY_MATCHING_INFO_REQ,
	UG_PARTY_MATCHING_ENTER_DUNGEON_REQ,
	UG_PARTY_MATCHING_ENTER_DUNGEON_AGREE_NFY,
	UG_DWC_WORLDCOUNT_INFO_REQ,
	UG_DWC_ENTER_REQ,
	UG_DWC_ENTER_CONFIRM_REQ,
	UG_DWC_SCENARIO_INFO_REQ,
	UG_DWC_GET_REWARD_REQ,
	UG_CHARTITLE_SELECT_REQ,
	UG_TMQ_LIMIT_COUNT_PLUS_REQ,
	UG_PARTY_SELECT_STATE_REQ,
	UG_BATTLE_DUNGEON_ENTER_REQ,
	UG_BATTLE_DUNGEON_LEAVE_REQ,
	UG_ITEM_UPGRADE_WORK_REQ,
	UG_ITEM_UPGRADE_PROBABLEITEM_REQ,
	UG_REQUEST_CHAR_HISTORY_DATA_REQ,
	UG_EVENT_REWARD_LOAD_REQ,
	UG_EVENT_REWARD_SELECT_REQ,
	UG_DROPITEM_INFO_REQ,
	UG_ITEM_UPGRADE_BY_COUPON_REQ,
	UG_VEHICLE_FUEL_INSERT_REQ,
	UG_ITEM_EXCHANGE_REQ,
	UG_GAMEGUARD3_AUTH_ANSWER_RES,
	UG_ITEM_UPGRADED_EXCHANGE_REQ,
	UG_ITEM_SEAL_REQ,
	UG_ITEM_SEAL_EXTRACT_REQ,
	UG_PERFORMANCE_DATA_NFY,
	UG_PERFORMANCE_DATA_2_NFY,
	UG_PARTY_CHANGE_ITEM_LOOTING_RANK_METHOD_REQ,
	UG_ITEM_DICE_REQ,
	UG_GIFT_SHOP_START_REQ,
	UG_GIFT_SHOP_BUY_REQ,
	UG_ITEM_SOCKET_INSERT_BEAD_REQ,
	UG_ITEM_SOCKET_DESTROY_BEAD_REQ,
	UG_ITEM_CHAGE_BATTLE_ATTRIBUTE_REQ,
	UG_INVISIBLE_COSTUME_UPDATE_REQ,
	UG_INVENTORY_SORT_REQ,
	UG_ITEM_CHANGE_OPTION_REQ,
	UG_DYNAMIC_FIELD_SYSTEM_BOSS_POSITION_REQ,
	UG_CHAR_AIR_MOVE,
	UG_CHAR_AIR_JUMP,
	UG_CHAR_AIR_DASH,
	UG_CHAR_AIR_FALLING,
	UG_CHAR_AIR_END,
	UG_CHAR_AIR_FOLLOW_MOVE,
	UG_CHAR_AIR_ACCEL,
	UG_CHAR_AIR_POSE_REQ,
	UG_PET_ATTACK_TOGGLE_NFY,
	UG_PET_SKILL_TOGGLE_NFY,
	UG_PET_RECALL_NFY,
	UG_MASCOT_FUSION_REQ,
	UG_MASCOT_SKILL_ADD_REQ,
	UG_MASCOT_SKILL_UPDATE_REQ,
	UG_MASCOT_SKILL_UPGRADE_REQ,
	UG_MASCOT_SKILL_REQ,
	UG_MASCOT_AUTO_LOOTING_REQ,
	UG_MASCOT_REMOTE_SHOP_SELL_REQ,
	UG_MASCOT_SEAL_SET_REQ,
	UG_MASCOT_SEAL_CLEAR_REQ,

	/*	***********************************	*/
	/*			Game -> User				*/
	/*	***********************************	*/

	GU_OPCODE_BEGIN = 5000,

	GU_AVATAR_INFO_END,
	GU_AVATAR_ATTRIBUTE_UPDATE,
	GU_AVATAR_HTB_INFO,
	GU_AVATAR_BUFF_INFO,
	GU_AVATAR_WORLD_INFO,
	GU_AVATAR_ZONE_INFO,
	GU_AVATAR_CHAR_INFO,
	GU_AVATAR_ITEM_INFO,
	GU_AVATAR_SKILL_INFO,
	GU_AVATAR_QUEST_COMPLETE_INFO,
	GU_AVATAR_QUEST_PROGRESS_INFO,
	GU_AVATAR_QUEST_INVENTORY_INFO,
	GU_PONG,
	GU_SESSION_STATE_WRONG,
	GU_CHAR_STATE_WRONG,
	GU_OBJECT_CREATE,
	GU_OBJECT_DESTROY,
	GU_ENTER_WORLD_RES,
	GU_ENTER_WORLD_COMPLETE,
	GU_AUTH_KEY_FOR_COMMUNITY_SERVER_RES,
	GU_GAME_ENTER_RES,
	GU_GAME_LEAVE_RES,
	GU_CHAR_JUMP,
	GU_CHAR_AIR_MOVE_SYNC,
	GU_CHAR_CHANGE_JUMP_DIRECTION,
	GU_CHAR_CHANGE_DIRECTION_ON_FLOATING,
	GU_CHAR_JUMP_END,
	GU_CHAR_SPECIAL_ATTACK_NFY,
	GU_CHAR_FOLLOW_MOVE,
	GU_CHAR_FOLLOW_MOVE_SYNC,
	GU_CHAR_FIGHTMODE,
	GU_CHAR_BLOCK_MODE_COOL_TIME_NFY,
	GU_CHAR_MOVE,
	GU_CHAR_DEST_MOVE,
	GU_CHAR_CHANGE_HEADING,
	GU_CHAR_MOVE_COLLISION,
	GU_CHAR_MOVE_COLLISION_END,
	GU_CHAR_STANDING_SLIP_END,
	GU_CHAR_CAMPING,
	GU_CHAR_KNOCKDOWN,
	GU_CHAR_FAINT,
	GU_CHAR_SLIDING,
	GU_CHAR_AWAY_RES,
	GU_CHAR_MAIL_INFO,
	GU_CHAR_KEY_INFO,
	GU_CHAR_RANKBATTLE_SCORE,
	GU_CHAR_CHANNEL_CHANGE_RES,
	GU_CHAR_EXIT_RES,
	GU_CHAR_SKILL_RES,
	GU_CHAR_DIRECT_PLAY_CANCEL_NFY,
	GU_CHAR_DIRECT_PLAY_END,
	GU_CHAR_KEY_UPDATE_RES,
	GU_CHAR_REVIVAL_RES,
	GU_CHAR_TELEPORT_RES,
	GU_CHAR_CONVERT_CLASS,
	GU_CHAR_DIALOG,
	GU_CHAR_DIRECT_PLAY,
	GU_CHAR_BIND_RES,
	GU_CHAR_SERVER_CHANGE_RES,
	GU_CHAR_ACTION_ATTACK,
	GU_CHAR_ACTION_SKILL,
	GU_CHAR_ACTION_ITEM,
	GU_GAME_EXIT_RES,
	GU_GAME_KICK_NFY,
	GU_EFFECT_AFFECTED,
	GU_CHAR_LP_EP_RECOVERED,
	GU_CHANGED_CHAR_NICKNAME_NFY,
	GU_CHANGED_CHAR_SIZE_NFY,
	GU_CHANGED_NPC_RELATION_PC_NFY,
	GU_SKILL_TARGET_LIST_REQ,
	GU_SKILL_CASTING_DELAYED_NFY,
	GU_SKILL_AFFECTING_CANCELED_NFY,
	GU_SKILL_LEARN_RES,
	GU_SKILL_LEARN_BY_ITEM_RES,
	GU_SKILL_CASTING_CANCELED_NFY,
	GU_SKILL_AFTEREFFECT_REMAINING_TIME_NFY,
	GU_SKILL_COOL_TIME_STARTED_NFY,
	GU_SKILL_RP_BONUS_SETTING_RES,
	GU_SKILL_LEARNED_NFY,
	GU_SKILL_UPGRADE_RES,
	GU_SKILL_NOTIFY_EXP,
	GU_HTB_LEARN_RES,
	GU_HTB_RP_BALL_USED_NFY,
	GU_HTB_START_RES,
	GU_HTB_RP_BALL_RESULT_DECIDED_NFY,
	GU_HTB_FORWARD_RES,
	GU_HTB_RP_BALL_USE_RES,
	GU_BUFF_REFRESH_ALL,
	GU_BUFF_REGISTERED,
	GU_BUFF_DROPPED,
	GU_BUFF_DROP_RES,
	GU_BUFF_ACTIVATE,
	GU_BUFF_PARAMETER_CHANGED_NFY,
	GU_ITEM_EQUIP_REPAIR_RES,
	GU_ITEM_REPAIR_RES,
	GU_ITEM_DELETE_RES,
	GU_ITEM_UPDATE,
	GU_ITEM_IDENTIFY_RES,
	GU_ITEM_MOVE_STACK_RES,
	GU_ITEM_CASTING_DELAYED_NFY,
	GU_ITEM_UPGRADE_RES,
	GU_ITEM_MOVE_RES,
	GU_ITEM_CREATE,
	GU_ITEM_DELETE,
	GU_ITEM_DUR_DOWN,
	GU_ITEM_DUR_UPDATE,
	GU_ITEM_STACK_UPDATE,
	GU_ITEM_USE_RES,
	GU_ITEM_CASTING_CANCELED,
	GU_ZENNY_PICK_RES,
	GU_ITEM_PICK_RES,
	GU_PARTY_ZENNY_LOOTING_METHOD_UNLOCKED_NFY,
	GU_PARTY_ITEM_LOOTING_METHOD_UNLOCKED_NFY,
	GU_PARTY_ZENNY_UPDATED_NFY,
	GU_PARTY_INVENTORY_ITEM_ADDED_NFY,
	GU_PARTY_INVENTORY_ITEM_REMOVED_NFY,
	GU_PARTY_MEMBER_GAINED_ITEM_NFY,
	GU_PARTY_CHANGE_ZENNY_LOOTING_METHOD_RES,
	GU_PARTY_ZENNY_LOOTING_METHOD_CHANGED_NFY,
	GU_PARTY_CHANGE_ITEM_LOOTING_METHOD_RES,
	GU_PARTY_ITEM_LOOTING_METHOD_CHANGED_NFY,
	GU_PARTY_MEMBER_GAINED_ZENNY_NFY,
	GU_PARTY_MEMBER_LOCATION_NFY,
	GU_UPDATE_CHAR_CONDITION,
	GU_UPDATE_CHAR_ATTACK_SPEEDRATE,
	GU_UPDATE_CHAR_LP_EP,
	GU_UPDATE_CHAR_ZENNY,
	GU_UPDATE_CHAR_LP,
	GU_UPDATE_CHAR_EP,
	GU_UPDATE_CHAR_RP,
	GU_UPDATE_CHAR_EXP,
	GU_UPDATE_ITEM_EQUIP,
	GU_UPDATE_ITEM_DELETED,
	GU_UPDATE_CHAR_LEVEL,
	GU_UPDATE_CHAR_SPEED,
	GU_UPDATE_CHAR_STATE,
	GU_UPDATE_CHAR_ASPECT_STATE,
	GU_UPDATE_CHAR_MUDOSA_POINT,
	GU_SYSTEM_DISPLAY_TEXT,
	GU_SYSTEM_DISPLAY_SCRIPT_TEXT,
	GU_SYSTEM_DISPLAY_RESULTCODE,
	GU_SHOP_SKILL_BUY_RES,
	GU_SHOP_SELL_RES,
	GU_SHOP_START_RES,
	GU_SHOP_BUY_RES,
	GU_SHOP_END_RES,
	GU_PARTY_DISBANDED_NFY,
	GU_PARTY_CREATE_RES,
	GU_PARTY_DISBAND_RES,
	GU_PARTY_RESPONSE_INVITATION_RES,
	GU_PARTY_OPENED_CHARM_INVENTORY_INFO,
	GU_PARTY_KICK_OUT_RES,
	GU_PARTY_MEMBER_KICKED_OUT_NFY,
	GU_PARTY_CHANGE_LEADER_RES,
	GU_PARTY_INVITATION_DECLINED_NFY,
	GU_PARTY_INVITATION_EXPIRED_NFY,
	GU_PARTY_MEMBER_JOINED_NFY,
	GU_PARTY_INFO,
	GU_PARTY_LEAVE_RES,
	GU_PARTY_INVITE_RES,
	GU_PARTY_INVITE_NFY,
	GU_PARTY_MEMBER_LEFT_NFY,
	GU_PARTY_LEADER_CHANGED_NFY,
	GU_PARTY_MEMBER_LEVELED_UP_NFY,
	GU_PARTY_MEMBER_CLASS_CHANGED_NFY,
	GU_QUEST_ITEM_CREATE_NFY,
	GU_QUEST_ITEM_DELETE_NFY,
	GU_QUEST_ITEM_UPDATE_NFY,
	GU_QUEST_ITEM_MOVE_RES,
	GU_QUEST_ITEM_DELETE_RES,
	GU_QUEST_SVREVT_START_NFY,
	GU_QUEST_SVREVT_END_NFY,
	GU_QUEST_SVREVT_UPDATE_NFY,
	GU_QUEST_GIVEUP_RES,
	GU_QUEST_SHARE_NFY,
	GU_QUEST_RESET_NFY,
	GU_QUEST_OBJECT_VISIT_RES,
	GU_QUEST_FORCED_COMPLETION_NFY,
	GU_SOCIAL_ACTION,
	GU_SCOUTER_INDICATOR_RES,
	GU_SCOUTER_PREDICT_RES,
	GU_SCOUTER_EQUIP_CHECK_RES,
	GU_SCOUTER_CHIP_REMOVE_ALL_RES,
	GU_BANK_START_RES,
	GU_BANK_MOVE_RES,
	GU_BANK_MOVE_STACK_RES,
	GU_BANK_END_RES,
	GU_BANK_ZENNY_INFO,
	GU_BANK_ITEM_INFO,
	GU_BANK_ZENNY_RES,
	GU_BANK_BUY_RES,
	GU_BANK_ITEM_DELETE_RES,
	GU_TS_CONFIRM_STEP_RES,
	GU_TS_UPDATE_SYNC_NFY,
	GU_TS_UPDATE_STATE,
	GU_TS_UPDATE_EVENT_NFY,
	GU_TS_EXCUTE_TRIGGER,
	GU_TS_EXCUTE_TRIGGER_OBJECT_RES,
	GU_TS_TRIGGER_OBJECT_DIALOG_NFY,
	GU_TS_PC_DIALOG_NFY,
	GU_TS_SKIP_CONTAINER,
	GU_TIMEQUEST_ENTER_RES,
	GU_TIMEQUEST_ENTER_DIRECTION_NFY,
	GU_TIMEQUEST_START_NFY,
	GU_TIMEQUEST_START_EXCEPTION_NFY,
	GU_TIMEQUEST_LEAVE_NFY,
	GU_TIMEQUEST_COUNTDOWN_NFY,
	GU_TIMEQUEST_REWARD_NFY,
	GU_TIMEQUEST_INFORMATION_NFY,
	GU_TIMEQUEST_UPDATE_GAME_STATE,
	GU_TIMEQUEST_UPDATE_KILL_COUNT,
	GU_TIMEQUEST_UPDATE_COUPON_COUNT,
	GU_TIMEQUEST_UPDATE_TMQ_POINT,
	GU_TIMEQUEST_UPDATE_GAME_TIME,
	GU_FREEBATTLE_CHALLENGE_RES,
	GU_FREEBATTLE_ACCEPT_REQ,
	GU_FREEBATTLE_CANCEL_NFY,
	GU_FREEBATTLE_START_NFY,
	GU_FREEBATTLE_OUTSIDE_NFY,
	GU_FREEBATTLE_INSIDE_NFY,
	GU_FREEBATTLE_END_NFY,
	GU_QUICK_SLOT_UPDATE_RES,
	GU_QUICK_SLOT_DEL_NFY,
	GU_QUICK_SLOT_INFO,
	GU_PET_CHAR_INFO,
	GU_PET_SKILL_INFO,
	GU_PET_INFO_END,
	GU_PET_DESPAWNED_NFY,
	GU_PET_DISMISS_PET_RES,
	GU_ACTION_REPORT_MESSAGE,
	GU_TRADE_START_NFY,
	GU_TRADE_START_RES,
	GU_TRADE_OK_REQ,
	GU_TRADE_ADD_NFY,
	GU_TRADE_ADD_RES,
	GU_TRADE_DEL_NFY,
	GU_TRADE_DEL_RES,
	GU_TRADE_MODIFY_NFY,
	GU_TRADE_MODIFY_RES,
	GU_TRADE_ZENNY_UPDATE_NFY,
	GU_TRADE_ZENNY_UPDATE_RES,
	GU_TRADE_END_NFY,
	GU_TRADE_END_RES,
	GU_TRADE_CANCEL_NFY,
	GU_TRADE_CANCEL_RES,
	GU_TRADE_DENY_RES,
	GU_GUILD_NAME_CHANGED_NFY,
	GU_GUILD_CREATE_RES,
	GU_GUILD_INVITE_RES,
	GU_TOBJECT_UPDATE_STATE,
	GU_TOBJECT_ACTION_ATTACK,
	GU_TUTORIAL_HINT_UPDATE_RES,
	GU_TELECAST_MESSAGE_BEG_NFY,
	GU_TELECAST_MESSAGE_END_NFY,
	GU_BROAD_MESSAGE_BEG_NFY,
	GU_BROAD_MESSAGE_END_NFY,
	GU_MINI_NARRATION_NFY,
	GU_PROGRESS_MESSAGE_NFY,
	GU_DIRECTION_INDICATE_NFY,
	GU_RANKBATTLE_INFO_RES,
	GU_RANKBATTLE_JOIN_RES,
	GU_RANKBATTLE_JOIN_NFY,
	GU_RANKBATTLE_LEAVE_RES,
	GU_RANKBATTLE_LEAVE_NFY,
	GU_RANKBATTLE_MATCH_START_NFY,
	GU_RANKBATTLE_MATCH_CANCELED_NFY,
	GU_TUTORIAL_WAIT_NFY,
	GU_TUTORIAL_WAIT_CANCEL_RES,
	GU_TUTORIAL_PLAY_QUIT_RES,
	GU_RANKBATTLE_BATTLE_STATE_UPDATE_NFY,
	GU_RANKBATTLE_BATTLE_TEAM_INFO_NFY,
	GU_RANKBATTLE_BATTLE_PLAYER_STATE_NFY,
	GU_RANKBATTLE_BATTLE_KILLSCORE_UPDATE_NFY,
	GU_RANKBATTLE_BATTLE_STAGE_FINISH_NFY,
	GU_RANKBATTLE_BATTLE_MATCH_FINISH_NFY,
	GU_RANKBATTLE_BATTLE_END_NFY,
	GU_RANKBATTLE_BATTLE_FORCED_LEAVE_NFY,
	GU_RANKBATTLE_TOTAL_SCORE_UPDATE_NFY,
	GU_RANKBATTLE_STAGE_CLEAR_TIME_NFY,
	GU_DRAGONBALL_CHECK_RES,
	GU_DRAGONBALL_REWARD_RES,
	GU_DRAGONBALL_COLLECT_NFY,
	GU_DRAGONBALL_SCHEDULE_INFO,
	GU_PRIVATESHOP_CREATE_RES,
	GU_PRIVATESHOP_CREATE_NFY,
	GU_PRIVATESHOP_EXIT_RES,
	GU_PRIVATESHOP_OPEN_RES,
	GU_PRIVATESHOP_OPEN_NFY,
	GU_PRIVATESHOP_CLOSE_RES,
	GU_PRIVATESHOP_CLOSE_NFY,
	GU_PRIVATESHOP_BUSINESS_REQUEST_RES,
	GU_PRIVATESHOP_BUSINESS_REQUEST_NFY,
	GU_PRIVATESHOP_BUSINESS_CONSENT_REQ,
	GU_PRIVATESHOP_BUSINESS_CONSENT_NFY,
	GU_PRIVATESHOP_BUSINESS_WAITTIMEOUT_NFY,
	GU_PRIVATESHOP_BUSINESS_PRICEFLUCTUATIONS_RES,
	GU_PRIVATESHOP_BUSINESS_PRICEFLUCTUATIONS_NFY,
	GU_PRIVATESHOP_BUSINESS_IMMEDIATE_ITEM_BUYING_RES,
	GU_PRIVATESHOP_BUSINESS_IMMEDIATE_ITEM_BUYING_NFY,
	GU_PRIVATESHOP_BUSINESS_WINDOWCLOSE_NFY,
	GU_PRIVATESHOP_BUSINESS_CANCEL_RES,
	GU_PRIVATESHOP_BUSINESS_CANCEL_NFY,
	GU_PRIVATESHOP_ITEM_INSERT_RES,
	GU_PRIVATESHOP_ITEM_UPDATE_RES,
	GU_PRIVATESHOP_ITEM_DELETE_RES,
	GU_PRIVATESHOP_ITEM_BUYING_RES,
	GU_PRIVATESHOP_ITEM_BUYING_NFY,
	GU_PRIVATESHOP_ENTER_RES,
	GU_PRIVATESHOP_LEAVE_RES,
	GU_PRIVATESHOP_ITEM_DATA_INFO,
	GU_PRIVATESHOP_ITEM_SELECT_RES,
	GU_PRIVATESHOP_ITEM_SELECT_NFY,
	GU_PRIVATESHOP_ITEM_STATE_NFY,
	GU_PRIVATESHOP_LEAVE_NFY,
	GU_MAIL_START_RES,
	GU_MAIL_SEND_RES,
	GU_MAIL_READ_RES,
	GU_MAIL_RELOAD_NFY,
	GU_MAIL_DEL_RES,
	GU_MAIL_RETURN_RES,
	GU_MAIL_RELOAD_RES,
	GU_MAIL_LOAD_RES,
	GU_MAIL_LOAD_DATA,
	GU_MAIL_LOAD_INFO,
	GU_MAIL_ITEM_RECEIVE_RES,
	GU_MAIL_LOCK_RES,
	GU_MAIL_CLOSE_NFY,
	GU_MAIL_MULTI_DEL_RES,
	GU_MATCH_MINORMATCH_STATE_UPDATE_NFY,
	GU_MATCH_MINORMATCH_TEAM_INFO_NFY,
	GU_MATCH_MINORMATCH_PLAYER_STATE_NFY,
	GU_MATCH_MINORMATCH_UPDATE_SCORE_NFY,
	GU_MATCH_MINORMATCH_TEAM_SCORE_NFY,
	GU_MATCH_MINORMATCH_SELECTION_NFY,
	GU_MATCH_MINORMATCH_STAGE_FINISH_NFY,
	GU_MATCH_MINORMATCH_MATCH_FINISH_NFY,
	GU_MATCH_MAJORMATCH_STATE_UPDATE_NFY,
	GU_MATCH_MAJORMATCH_TEAM_INFO_NFY,
	GU_MATCH_MAJORMATCH_PLAYER_STATE_NFY,
	GU_MATCH_MAJORMATCH_UPDATE_SCORE_NFY,
	GU_MATCH_MAJORMATCH_STAGE_FINISH_NFY,
	GU_MATCH_MAJORMATCH_MATCH_FINISH_NFY,
	GU_MATCH_FINALMATCH_STATE_UPDATE_NFY,
	GU_MATCH_FINALMATCH_TEAM_INFO_NFY,
	GU_MATCH_FINALMATCH_PLAYER_STATE_NFY,
	GU_MATCH_FINALMATCH_UPDATE_SCORE_NFY,
	GU_MATCH_FINALMATCH_STAGE_FINISH_NFY,
	GU_MATCH_FINALMATCH_MATCH_FINISH_NFY,
	GU_MATCH_AWARDING_NFY,
	GU_SKILL_CONFUSE_TARGET_NFY,
	GU_SKILL_TERROR_COURSE_CHANGE_NFY,
	GU_DICE_ROLL_RES,
	GU_DICE_ROLLED_NFY,
	GU_BUDOKAI_STATE_INFO_NFY,
	GU_BUDOKAI_UPDATE_STATE_NFY,
	GU_BUDOKAI_UPDATE_MATCH_STATE_NFY,
	GU_BUDOKAI_JOIN_INDIVIDUAL_RES,
	GU_BUDOKAI_LEAVE_INDIVIDUAL_RES,
	GU_BUDOKAI_JOIN_TEAM_INFO_RES,
	GU_BUDOKAI_JOIN_TEAM_RES,
	GU_BUDOKAI_JOIN_TEAM_NFY,
	GU_BUDOKAI_LEAVE_TEAM_RES,
	GU_BUDOKAI_LEAVE_TEAM_NFY,
	GU_BUDOKAI_LEAVE_TEAM_MEMBER_RES,
	GU_BUDOKAI_LEAVE_TEAM_MEMBER_NFY,
	GU_BUDOKAI_JOIN_INFO_RES,
	GU_BUDOKAI_JOIN_STATE_RES,
	GU_BUDOKAI_JOIN_STATE_NFY,
	GU_BUDOKAI_MUDOSA_INFO_RES,
	GU_BUDOKAI_MUDOSA_TELEPORT_RES,
	GU_BUDOKAI_PROGRESS_MESSAGE_NFY,
	GU_BUDOKAI_SOCIAL_ACTION_NFY,
	GU_BUDOKAI_PRIZEWINNER_NAME_RES,
	GU_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_RES,
	GU_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_RES,
	GU_BUDOKAI_GM_MATCH_PROGRESS_INFO_RES,
	GU_BUDOKAI_GM_MATCH_ARENA_ENTER_RES,
	GU_BUDOKAI_GM_MATCH_ARENA_LEAVE_RES,
	GU_DISCONNECTED_NFY,
	GU_BOT_BOTCAUTION_HELPME_NFY,
	GU_SCOUTER_TURN_ON_NFY,
	GU_SCOUTER_TURN_OFF_NFY,
	GU_SCOUTER_BROKEN_NFY,
	GU_SCOUTER_ITEM_SELL_RES,
	GU_SHOP_EVENTITEM_START_RES,
	GU_SHOP_EVENTITEM_BUY_RES,
	GU_SHOP_EVENTITEM_END_RES,
	GU_ITEM_REPLACE,
	GU_SHOP_GAMBLE_BUY_RES,
	GU_PARTY_DUNGEON_DIFF_NFY,
	GU_PARTY_DUNGEON_DIFF_RES,
	GU_PARTY_DUNGEON_INIT_NFY,
	GU_PARTY_DUNGEON_INIT_RES,
	GU_UPDATE_CHAR_SP,
	GU_SKILL_INIT_RES,
	GU_SKILL_REMOVE_NFY,
	GU_HTB_REMOVE_NFY,
	GU_TELEPORT_PROPOSAL_NFY,
	GU_TELEPORT_CONFIRM_RES,
	GU_AVATAR_PETITION_INFO,
	GU_GAME_COMMON_MSG_NFY,
	GU_CHAR_TARGET_LOST_NFY,
	GU_CHAR_GUARD_CRASHED_NFY,
	GU_UPDATE_CHAR_RP_BALL,
	GU_UPDATE_CHAR_RP_BALL_MAX,
	GU_HOIPOIMIX_JOB_SET_RES,
	GU_HOIPOIMIX_JOB_RESET_RES,
	GU_AVATAR_RP_INCREASE_START_NFY,
	GU_AVATAR_RP_DECREASE_START_NFY,
	GU_AVATAR_RP_INCREASE_STOP_NFY,
	GU_HOIPOIMIX_RECIPE_REG_NFY,
	GU_HOIPOIMIX_ITEM_CHECK_RES,
	GU_HOIPOIMIX_ITEM_MAKE_RES,
	GU_HOIPOIMIX_ITEM_MAKE_EP_RES,
	GU_HOIPOIMIX_ITEM_RECIPE_INFO,
	GU_DYNAMIC_OBJECT_UPDATE_STATE,
	GU_HOIPOIMIX_ITEM_MACHINE_DEL_RES,
	GU_HOIPOIMIX_ITEM_MAKE_EXP_NFY,
	GU_HOIPOIMIX_ITEM_MAKE_EX_RES,
	GU_ITEM_DISASSEMBLE_RES,
	GU_HTB_LAST_STEP_CHANGED_NFY,
	GU_CHAR_CHARGE_CANCELED_NFY,
	GU_CHAR_REFRESH_LP_EP,
	GU_CHAR_NONBATTLEACTIONPATTERNSET_UNITIDX_NFY,
	GU_DOJO_CREATE_RES,
	GU_DOJO_DELETE_RES,
	GU_DOJO_FUNCTION_ADD_RES,
	GU_DOJO_BANK_HISTORY_RES,
	GU_DOGI_CREATE_RES,
	GU_DOGI_CHANGE_RES,
	GU_DOGI_UPDATE_NFY,
	GU_GUILD_DOGI_CREATE_RES,
	GU_GUILD_DOGI_CHANGE_RES,
	GU_VEHICLE_START_NFY,
	GU_VEHICLE_ENGINE_START_RES,
	GU_VEHICLE_ENGINE_START_NFY,
	GU_VEHICLE_ENGINE_STOP_RES,
	GU_VEHICLE_ENGINE_STOP_NFY,
	GU_VEHICLE_FUEL_UPDATE_NFY,
	GU_VEHICLE_END_RES,
	GU_VEHICLE_END_NFY,
	GU_VEHICLE_STUNT_NFY,
	GU_SKILL_PASSIVE_EFFECT_APPLIED_NFY,
	GU_AVATAR_UPDATED_SKILL_DATA_INFO,
	GU_MONSTER_TRANSFORMED_NFY,
	GU_GMT_COUNT_INFO_NFY,
	GU_UPDATE_BANK_DURATION_INFO_NFY,
	GU_CREATE_BANK_NFY,
	GU_PREMIUM_SLOT_COUNT_INFO_NFY,
	GU_CHILD_ADULT_SWITCHED_NFY,
	GU_CHANGE_CLASS_AUTHORITY_CHANGED_NFY,
	GU_PLAY_BGM,
	GU_PLAY_JINGLE,
	GU_DOJO_MARK_CHANGED_NFY,
	GU_DOJO_LEVEL_CHANGED_NFY,
	GU_UPDATE_CHAR_NETP,
	GU_DOJO_SCRAMBLE_RES,
	GU_DOJO_SCRAMBLE_RESPONSE_RES,
	GU_NETMARBLEMEMBERIP_NFY,
	GU_BUS_LOCATION_NFY,
	GU_BUS_LOCATION_ERASED_NFY,
	GU_BUS_LOCATION_RESET_ALL_NFY,
	GU_ITEM_EXPIRED_NFY,
	GU_SHOP_NETPYITEM_START_RES,
	GU_SHOP_NETPYITEM_BUY_RES,
	GU_SHOP_NETPYITEM_END_RES,
	GU_CHAR_REFRESH_BATTLE_ATTRIBUTE_MODIFIER,
	GU_CHAR_RANKBATTLE_ALLOW_NFY,
	GU_CHAR_RANKPOINT_RESET_NFY,
	GU_DOJO_NPC_INFO_RES,
	GU_GAMEGUARD_AUTH_ANSWER_REQ,
	GU_DOJO_SEAL_ATTACK_BEGIN_NFY,
	GU_DOJO_SEAL_ATTACK_END_NFY,
	GU_DOJO_SEAL_CURRENT_STATE_NFY,
	GU_INVENTORY_CAPSULE_UNLOCK_NFY,
	GU_DOJO_SCRAMBLE_SHIFT_SEAL_STATE_NFY,
	GU_UPDATE_CHAR_LP_STATUS_NFY,
	GU_DURATION_ITEM_BUY_RES,
	GU_DURATION_RENEW_RES,
	GU_CASHITEM_START_RES,
	GU_CASHITEM_INFO_RES,
	GU_CASHITEM_END_RES,
	GU_CASHITEM_MOVE_RES,
	GU_CASHITEM_USE_RES,
	GU_CASHITEM_ADD_NFY,
	GU_CASHITEM_DEL_NFY,
	GU_CASHITEM_HLSHOP_START_RES,
	GU_CASHITEM_HLSHOP_END_RES,
	GU_CASHITEM_HLSHOP_REFRESH_RES,
	GU_CASHITEM_BUY_RES,
	GU_CASHITEM_SEND_GIFT_RES,
	GU_CASHITEM_RECV_GIFT_NFY,
	GU_BUDOKAI_PRIZEWINNER_TEAM_NAME_RES,
	GU_GMT_INFO_NFY,
	GU_GMT_UPDATE_RES,
	GU_GMT_CHANGED_NFY,
	GU_GMT_APPLY_NFY,
	GU_UPDATE_CHAR_MAX_LP,
	GU_UPDATE_CHAR_MAX_EP,
	GU_UPDATE_CHAR_MAX_RP,
	GU_DOJO_SCRAMBLE_RECEIVE_INFO_NFY,
	GU_SCS_CHECK_START_REQ,
	GU_SCS_CHECK_REQ,
	GU_SCS_REPLY_RES,
	GU_SCS_REMAKE_RES,
	GU_SCS_CHECK_OVERTIME_NFY,
	GU_SERVER_CHANNEL_INFO_REFRESHED_NFY,
	GU_QUICK_TELEPORT_LOAD_RES,
	GU_QUICK_TELEPORT_UPDATE_RES,
	GU_QUICK_TELEPORT_DEL_RES,
	GU_QUICK_TELEPORT_USE_RES,
	GU_PARTY_MEMBER_SUPERIOR_EFFECT_UPDATE_NFY,
	GU_SUPERIOR_EFFECT_TYPE_UPDATE_NFY,
	GU_CHAR_RANKBATTLE_REMAIN_COUNT_NFY,
	GU_CHAR_TIMEQUEST_LIMIT_COUNT_NFY,
	GU_SCS_CHECK_CANCEL_NFY,
	GU_SKILL_INIT_NFY,
	GU_CHAR_CRESCENT_POPO_REVIVAL_RES,
	GU_CHARACTER_RENAME_RES,
	GU_CHAR_PARTY_POPO_REJECT_NFY,
	GU_CASHITEM_UPDATE_DURATION_RES,
	GU_NPC_SERVER_DOWN_NFY,
	GU_MARBLEBANK_LOGIN_NFY,
	GU_DRAGONBALL_SCRAMBLE_JOIN_RES,
	GU_DRAGONBALL_SCRAMBLE_JOIN_NFY,
	GU_DRAGONBALL_SCRAMBLE_BALL_LOC_UPDATE_NFY,
	GU_DRAGONBALL_SCRAMBLE_BALL_LOC_RES,
	GU_DRAGONBALL_SCRAMBLE_SEASON_STATE_NFY,
	GU_DRAGONBALL_SCRAMBLE_HAS_BALL_NFY,
	GU_DRAGONBALL_SCRAMBLE_MESSAGE_NFY,
	GU_DRAGONBALL_SCRAMBLE_REWARDED_NFY,
	GU_CHAR_SKILL_INIT_RES,
	GU_SKILL_RESET_PLUS_RES,
	GU_PORTAL_INFO,
	GU_PORTAL_ADD_RES,
	GU_PORTAL_RES,
	GU_WAR_FOG_INFO,
	GU_WAR_FOG_UPDATE_RES,
	GU_MOB_LUCKY_DROP_NFY,
	GU_ITEM_UPGRADE_ALL_NFY,
	GU_BOT_BOTCAUTION_NFY,
	GU_UPDATE_CHAR_REPUTATION,
	GU_GUILD_FUNCTION_ADD_RES,
	GU_GUILD_GIVE_ZENNY_RES,
	GU_GUILD_BANK_START_RES,
	GU_GUILD_BANK_MOVE_RES,
	GU_GUILD_BANK_MOVE_STACK_RES,
	GU_GUILD_BANK_END_RES,
	GU_GUILD_BANK_ZENNY_INFO,
	GU_GUILD_BANK_ITEM_INFO,
	GU_GUILD_BANK_ZENNY_RES,
	GU_GUILD_CREATE_MARK_RES,
	GU_GUILD_CHANGE_MARK_RES,
	GU_GUILD_MARK_CHANGED_NFY,
	GU_CROSSFIRE_RES,
	GU_BANK_LOAD_RES,
	GU_GUILD_CHANGE_NAME_RES,
	GU_PARTY_SHARETARGET_RES,
	GU_PARTY_SHARETARGET_NFY,
	GU_RIDE_ON_BUS_RES,
	GU_RIDE_OFF_BUS_RES,
	GU_TRANSFORM_CANCEL_RES,
	GU_SHOP_ITEM_IDENTIFY_RES,
	GU_GUILD_DOGI_DYE_RES,
	GU_TENKAICHIDAISIJYOU_SELL_RES,
	GU_TENKAICHIDAISIJYOU_SELL_CANCEL_RES,
	GU_TENKAICHIDAISIJYOU_BUY_RES,
	GU_TENKAICHIDAISIJYOU_LIST_DATA,
	GU_TENKAICHIDAISIJYOU_LIST_RES,
	GU_MASCOT_REGISTER_RES,
	GU_MASCOT_SUMMON_RES,
	GU_MASCOT_UNSUMMON_RES,
	GU_MASCOT_SUMMON_EX_RES,
	GU_MASCOT_UNSUMMON_EX_RES,
	GU_MASCOT_DELETE_RES,
	GU_MASCOT_DELETE_EX_RES,
	GU_MASCOT_RING_ACTION_RES,
	GU_MASCOT_RING_REMOVE_ALL_RES,
	GU_MASCOT_CHANGE_VP,
	GU_MASCOT_CHANGE_EXP,
	GU_MASCOT_INFO,
	GU_MASCOT_INFO_EX,
	GU_MASCOT_REGISTER_NFY,
	GU_MASCOT_REGISTER_EX_NFY,
	GU_MASCOT_SP_CHANGE_NFY,
	GU_UPDATE_MASCOT_SUMMON,
	GU_MASCOT_RING_MATERIAL_DISASSEMBLE_RES,
	GU_MASCOT_RING_ACTION_END_RES,
	GU_REMOTE_SHOP_BUY_RES,
	GU_REMOTE_SHOP_SELL_RES,
	GU_MASCOT_EMOTION_NFY,
	GU_REMOTE_ITEM_EQUIP_REPAIR_RES,
	GU_REMOTE_ITEM_REPAIR_RES,
	GU_REMOTE_SHOP_ITEM_IDENTIFY_RES,
	GU_WORLD_FREE_PVP_ZONE_ENTERED_NFY,
	GU_WORLD_FREE_PVP_ZONE_LEFT_NFY,
	GU_WAGUWAGUMACHINE_COIN_INFO,
	GU_SKILL_ONE_RESET_RES,
	GU_ITEM_COOL_TIME_INFO,
	GU_AGGRO_LIST_NFY,
	GU_AGGRO_UPDATE_NFY,
	GU_AGGRO_RESET_NFY,
	GU_CHAR_TARGET_CHANGED,
	GU_SERVER_CONTENTS_ONOFF,
	GU_DWC_WORLDCOUNT_INFO_RES,
	GU_DWC_ENTER_RES,
	GU_DWC_ENTER_PROPOSAL_NFY,
	GU_DWC_ENTER_CONFIRM_RES,
	GU_DWC_ENTER_CANCELED_NFY,
	GU_DWC_ENTER_DIRECTION_NFY,
	GU_DWC_MISSION_REWARD_NFY,
	GU_DWC_SCENARIO_INFO_RES,
	GU_DWC_SCENARIO_UPDATE_NFY,
	GU_DWC_LIMIT_COUNT_NFY,
	GU_DWC_REWARD_LIST,
	GU_DWC_GET_REWARD_RES,
	GU_CHARTITLE_LIST_INFO,
	GU_CHARTITLE_SELECT_RES,
	GU_CHARTITLE_ADD,
	GU_CHARTITLE_DELETE,
	GU_PARTY_SELECT_STATE_NFY,
	GU_PARTY_SELECT_STATE_RES,
	GU_PARTY_SELECT_STATE_INIT_NFY,
	GU_TMQ_LIMIT_COUNT_PLUS_RES,
	GU_CHAR_TIMEQUEST_LIMIT_PLUS_COUNT_NFY,
	GU_CHAR_COORDINATE_EACH_TICK_NFY,
	GU_ULTIMATE_DUNGEON_ENTER_RES,
	GU_PARTY_MATCHING_REGISTER_RES,
	GU_PARTY_MATCHING_JOIN_RES,
	GU_PARTY_MATCHING_ROLEPLAY_SELECT_START_NFY,
	GU_PARTY_MATCHING_ROLEPLAY_RES,
	GU_PARTY_MATCHING_UNREGISTER_RES,
	GU_PARTY_MATCHING_LIST_RES,
	GU_PARTY_MATCHING_INFO_RES,
	GU_PARTY_MATCHING_ENTER_DUNGEON_AGREE_START_NFY,
	GU_PARTY_MATCHING_ENTER_DUNGEON_AGREE_NFY,
	GU_PARTY_MATCHING_ENTER_DUNGEON_RES,
	GU_BATTLE_DUNGEON_ENTER_RES,
	GU_BATTLE_DUNGEON_LEAVE_RES,
	GU_BATTLE_DUNGEON_STATE_UPATE_NFY,
	GU_BATTLE_DUNGEON_STAGE_CLEAR_NFY,
	GU_BATTLE_DUNGEON_LIMIT_TIME_START_NFY,
	GU_BATTLE_DUNGEON_LIMIT_TIME_END_NFY,
	GU_BATTLE_DUNGEON_FAIL_NFY,
	GU_BATTLE_DUNGEON_REWARD_FINISH_NFY,
	GU_BUFF_ADD_NFY,
	GU_EVENT_PLAY_TIME_NFY,
	GU_SERVERSCRIPT_COUNTDOWN_NFY,
	GU_SERVERSCRIPT_EVENTSTATUS_REGISTER_NFY,
	GU_SERVERSCRIPT_EVENTSTATUS_UPDATE_NFY,
	GU_SERVERSCRIPT_EVENTSTATUS_SELECT_NFY,
	GU_SERVERSCRIPT_EVENTSTATUS_CLEAR_NFY,
	GU_ITEM_UPGRADE_WORK_RES,
	GU_ITEM_UPGRADE_PROBABLEITEM_RES,
	GU_FORMULA_RESULT_EACH_TICK_NFY,
	GU_GAME_DATA_UPGRADED_ITEM_ABILITY,
	GU_ACHIEVEMENT_COMPLETE_NFY,
	GU_CHARTITLE_SELECT_NFY,
	GU_CHAR_HISTORY_DATA_RES,
	GU_ACHIEVEMENTS_COMPLETE_INFO,
	GU_CASHITEM_INFO,
	GU_TRIGGER_SYSTEM_ENABLED_NFY,
	GU_TRIGGER_SYSTEM_DISABLED_NFY,
	GU_EVENT_REWARD_LOAD_INFO,
	GU_EVENT_REWARD_LOAD_RES,
	GU_EVENT_REWARD_SELECT_RES,
	GU_ITEM_BULK_CREATE_INFO,
	GU_DROPITEM_INFO_RES,
	GU_EVENTMACHINE_COIN_INFO,
	GU_ITEM_UPGRADE_BY_COUPON_RES,
	GU_AUTO_RECOVER_NFY,
	GU_VP_AUTO_RECOVER_NFY,
	GU_EXP_AUTO_PORTION_NFY,
	GU_BATTLE_STATISTICS_EACH_TICK_NFY,
	GU_VEHICLE_FUEL_INSERT_RES,
	GU_ITEM_EXCHANGE_RES,
	GU_CHAR_IS_BATTLECOMBATING,
	GU_GAMEGUARD3_AUTH_ANSWER_REQ,
	GU_ITEM_UPGRADED_EXCHANGE_RES,
	GU_SERVER_SETTING_INFO_NFY,
	GU_ITEM_SEAL_RES,
	GU_ITEM_SEAL_EXTRACT_RES,
	GU_UPDATE_CHAR_SKILL_ANIMATION_SPEED_MODIFIER,
	GU_EVENT_COUNT_NFY,
	GU_PARTY_CHANGE_ITEM_LOOTING_RANK_METHOD_RES,
	GU_PARTY_CHANGE_ITEM_LOOTING_RANK_METHOD_NFY,
	GU_ITEM_DICE_RES,
	GU_ITEM_DICE_PARTY_NFY,
	GU_ITEM_DICE_RESULT_NFY,
	GU_ITEM_PICK_DICE_NFY,
	GU_GIFT_SHOP_INIT_RES,
	GU_GIFT_SHOP_START_RES,
	GU_GIFT_SHOP_TAB_INFO_NFY,
	GU_GIFT_SHOP_BUY_RES,
	GU_ITEM_SOCKET_INSERT_BEAD_RES,
	GU_ITEM_SOCKET_DESTROY_BEAD_RES,
	GU_ITEM_CHANGE_BATTLE_ATTRIBUTE_RES,
	GU_INVISIBLE_COSTUME_UPDATE_RES,
	GU_INVISIBLE_COSTUME_UPDATE_NFY,
	GU_INVENTORY_SORT_RES,
	GU_ITEM_CHANGE_OPTION_RES,
	GU_PLAY_RESTRICT_INFO_UPDATE_NFY,
	GU_PLAY_RESTRICT_TIME_NFY,
	GU_DYNAMIC_FIELD_SYSTEM_BOSS_POSITION_RES,
	GU_DYNAMIC_FIELD_COUNT_NFY,
	GU_BLESS_DEBUFF_MULTI_NFY,
	GU_SHUTDOWN_COUNT_DOWN_START_NFY,
	GU_UPDATE_CHAR_AP,
	GU_AIR_FAIL_INFO,
	GU_CHAR_SKY_DUNGEON_LIMIT_COUNT_NFY,
	GU_CAN_ACCEL_NFY,
	GU_RANKBATTLE_BATTLE_ORDER_INFO_NFY,
	GU_CHAR_AIR_POSE_RES,
	GU_CHAR_AIR_POSE_NFY,
	GU_MASCOT_FUSION_RES,
	GU_MASCOT_SKILL_ADD_RES,
	GU_MASCOT_SKILL_UPDATE_RES,
	GU_MASCOT_SKILL_UPGRADE_RES,
	GU_MASCOT_SKILL_RES,
	GU_MASCOT_REMOTE_SHOP_SELL_RES,
	GU_MASCOT_SKILL_ACTIVATE_NFY,
	GU_MASCOT_AUTO_LOOTING_RES,
	GU_MASCOT_SEAL_SET_RES,
	GU_MASCOT_SEAL_CLEAR_RES,
	GU_MASCOT_EX_EMOTION_NFY,
	GU_MASCOT_SKILLCOOLTIME_SET,
	GU_EVENT_SCHEDULING_START,
	GU_EVENT_SCHEDULING_END,
	GU_SCOUTER_ACTIVATION_RES,

	GU_OPCODE_END_DUMMY,
	GU_OPCODE_END = GU_OPCODE_END_DUMMY - 1,

	/*-----------------------------------------------*/

	//UG_PING, = UG_OPCODE_BEGIN,
	/*UG_GAME_ENTER_REQ,
	UG_GAME_LEAVE_REQ,									// 게임 나감
	UG_AUTH_KEY_FOR_COMMUNITY_SERVER_REQ,				// 커뮤니티 서버 인증키 요청
	UG_ENTER_WORLD,										// 월드 진입
	UG_SERVER_COMMAND,									// 서버 명령어

	UG_CHAR_READY_FOR_COMMUNITY_SERVER_NFY,				// 커뮤니티 서버와의 데이타 전송 준비가 되었음을 알림
	UG_CHAR_READY_TO_SPAWN,								// 로딩 완료(Spawning state로의 진입 준비 상태)
	UG_CHAR_READY,										// 캐릭터 준비
	UG_CHAR_MOVE,										// 캐릭터 이동
	UG_CHAR_DEST_MOVE,									// 캐릭터 목적지 이동
	UG_CHAR_CHANGE_HEADING,								// 캐릭터 회전
	UG_CHAR_MOVE_SYNC,									// 캐릭터 위치 보정
	UG_CHAR_CHANGE_DIRECTION_ON_FLOATING,				// 캐릭터 점프/falling 때의 바라보는 방향
	UG_CHAR_FOLLOW_MOVE,								// 캐릭터 타겟 따라가기
	UG_CHAR_DASH_KEYBOARD,								// Keyboard dash 시작
	UG_CHAR_DASH_MOUSE,									// Mouse dash 시작
	UG_CHAR_JUMP,										// 점프 시작
	UG_CHAR_JUMP_END,									// 점프 종료
	UG_CHAR_FALLING,									// Falling 상태 시작/종료
	UG_CHAR_TOGG_SITDOWN,								// 앉기모드 토글
	UG_CHAR_TOGG_FIGHTING,								// 전투모드 토글
	UG_CHAR_TOGG_RUNNING,								// 뛰기모드 토글 ( 현재 클라이언트는 사용하지 않음 )
	UG_CHAR_TARGET_SELECT,								// 타겟 선택
	UG_CHAR_TARGET_INFO,								// 타겟 정보 요청
	UG_CHAR_TARGET_FACING,								// 타겟 대면
	UG_CHAR_ATTACK_BEGIN,								// 공격 시작 알림
	UG_CHAR_ATTACK_END,									// 공격 종료 알림
	UG_CHAR_CHARGE,										// 캐릭터 기충전
	UG_CHAR_BLOCK_MODE,									// Block 모드 시작/종료
	UG_CHAR_TELEPORT_REQ,								// 텔레포트 요청
	UG_CHAR_BIND_REQ,									// 바인드 요청
	UG_CHAR_REVIVAL_REQ,								// 부활 요청
	UG_CHAR_SERVER_CHANGE_REQ,							// 다른 게임 서버로의 이동 요청
	UG_CHAR_CHANNEL_CHANGE_REQ,							// 캐릭터 나감 -> 다른 서버 채널로 이동 요청
	UG_CHAR_EXIT_REQ,									// 캐릭터 나감 -> 캐릭터 서버로 이동 요청
	UG_GAME_EXIT_REQ,									// 게임을 종료함
	UG_CHAR_AWAY_REQ,
	UG_CHAR_KEY_UPDATE_REQ,
	UG_CHAR_DIRECT_PLAY_ACK,							// 연출 종료후 보내주는 응답
	UG_CHAR_KNOCKDOWN_RELEASE_NFY,						// 넉다운 풀기
	UG_CHAR_SKILL_REQ,									// 스킬 사용 요청

	UG_SKILL_TARGET_LIST,								// 스킬 타겟 목록 알림
	UG_SKILL_LEARN_REQ,									// 스킬 수련 요청
	UG_SKILL_UPGRADE_REQ,								// 스킬 향상 요청
	UG_SKILL_RP_BONUS_SETTING_REQ,						// 스킬마다 자동으로 사용될 RP 보너스 타입 설정
	UG_HTB_START_REQ,								    // HTB 시작 요청
	UG_HTB_LEARN_REQ,									// HTB 습득 요청
	UG_HTB_FORWARD_REQ,									// HTB 진행
	UG_HTB_RP_BALL_USE_REQ,

	UG_BUFF_DROP_REQ,									// Buff 해제 요청

	UG_ITEM_MOVE_REQ,									// 아이템 이동 요청
	UG_ITEM_MOVE_STACK_REQ,								// 아이템 스택 이동 요청
	UG_ITEM_DELETE_REQ,									// 아이템 삭제 요청
	UG_ITEM_EQUIP_REPAIR_REQ,							// 수리 시작 요청
	UG_ITEM_PICK_REQ,									// 아이템줍기 요청
	UG_ITEM_REPAIR_REQ,
	UG_ITEM_USE_REQ,									// 아이템 사용 요청
	UG_ITEM_UPGRADE_REQ,								// 아이템 업그레이드
	UG_ITEM_IDENTIFY_REQ,								// 스카우터파츠로 아이템 확인

	UG_ZENNY_PICK_REQ,									// 돈줍기 요청

	UG_SHOP_START_REQ,									// 상점 열기
	UG_SHOP_BUY_REQ,									// 상점 물건 사기
	UG_SHOP_SELL_REQ,									// 상점 물건 팔기
	UG_SHOP_END_REQ,									// 상점 닫기
	UG_SHOP_SKILL_BUY_REQ,								// 스킬 구입 요청

	UG_PARTY_CREATE_REQ,								// 파티 만들기
	UG_PARTY_DISBAND_REQ,								// 파티 해산하기
	UG_PARTY_INVITE_REQ,								// 파티에 초대하기
	UG_PARTY_INVITE_CHARID_REQ,							// 파티에 초대하기(상대방의 CharID 이용)
	UG_PARTY_INVITE_CHAR_NAME_REQ,						// 파티에 초대하기(상대방의 이름 이용)
	UG_PARTY_RESPONSE_INVITATION,						// 파티 초대에 대한 대답 보내기
	UG_PARTY_LEAVE_REQ,									// 파티 탈퇴하기
	UG_PARTY_KICK_OUT_REQ,								// 멤버 강제로 탈퇴시키기
	UG_PARTY_CHANGE_LEADER_REQ,							// 파티 리더 변경하기
	UG_PARTY_OPEN_CHARM_SLOT_REQ,						// 파티 부적 등록창 열기
	UG_PARTY_CLOSE_CHARM_SLOT_REQ,						// 파티 부적 등록창 닫기
	UG_PARTY_REGISTER_VICTIM_ITEM_REQ,					// 부적 제물(아이템) 등록하기
	UG_PARTY_UNREGISTER_VICTIM_ITEM_REQ,				// 등록된 부적 제물(아이템) 다시 가져오기

	UG_PARTY_REGISTER_VICTIM_ZENNY_REQ,					// 부적 제물(제니) 등록하기
	UG_PARTY_UNREGISTER_VICTIM_ZENNY_REQ,				// 등록된 부적 제물(제니) 다시 가져오기
	UG_PARTY_DECLARE_ZENNY_REQ,							// 제니 등록하기
	UG_PARTY_ACTIVATE_CHARM_REQ,						// 부적 활성화하기
	UG_PARTY_DEACTIVATE_CHARM_REQ,						// 활성화된 부적 효과 제거하기
	UG_PARTY_CHANGE_ZENNY_LOOTING_METHOD_REQ,			// 제니 분배 방법 변경하기
	UG_PARTY_CHANGE_ITEM_LOOTING_METHOD_REQ,			// 아이템 분배 방법 변경하기
	UG_PARTY_INVEST_ZENNY_REQ,							// 제니를 파티 인벤토리의 아이템에 투자하기
	UG_PARTY_INVEN_ITEM_RANK_SET_REQ,					// 파티인벤에 넣을 아이템의 RANK설정하기

	UG_BANK_START_REQ,									// Warehouse 아이템 로딩
	UG_BANK_MOVE_REQ,									// Warehouse 의 아이템 이동
	UG_BANK_MOVE_STACK_REQ,								// Warehouse 의 스택아이템 이동
	UG_BANK_END_REQ,									// Warehouse 를 닫는다.
	UG_BANK_ZENNY_REQ,									// Warehouse 에 저금 혹은 인출한다.
	UG_BANK_BUY_REQ,									// Warehouse 의 창고가방을 늘린다.
	UG_BANK_ITEM_DELETE_REQ,							// Warehouse 의 아이템을 삭제한다.

	UG_SCOUTER_INDICATOR_REQ,							// 스카우터 전투력측정
	UG_SCOUTER_PREDICT_REQ,								// 스카우터 업그레이드 예측
	UG_SCOUTER_EQUIP_CHECK_REQ,							// 스카우터 상대 장착아이템 확인
	UG_SCOUTER_CHIP_REMOVE_ALL_REQ,						// 스카우터 칩을 모두 제거

	UG_SOCIAL_ACTION,									// Social Action 사용

	UG_TS_CONFIRM_STEP_REQ,								// 트리거 진행 요청
	UG_TS_UPDATE_STATE,									// 트리거 실패 상태 업데이트
	UG_TS_EXCUTE_TRIGGER_OBJECT,						// Excute Trigger Object

	UG_QUEST_ITEM_MOVE_REQ,								// 퀘스트 아이템 이동 요청
	UG_QUEST_ITEM_DELETE_REQ,							// 퀘스트 아이템 삭제 요청
	UG_QUEST_GIVEUP_REQ,								// 퀘스트 아이템 포기 요청
	UG_QUEST_SHARE,										// 퀘스트 공유 요청
	UG_QUEST_OBJECT_VISIT_REQ,							// npc, tobject 방문 이벤트

	UG_FREEBATTLE_CHALLENGE_REQ,						// 프리배틀 대전 신청
	UG_FREEBATTLE_ACCEPT_RES,							// 프리배틀 대전 수락응답

	UG_QUICK_SLOT_UPDATE_REQ,							// 빠른슬롯 추가 하거나 수정
	UG_QUICK_SLOT_DEL_REQ,								// 빠른슬롯 삭제

	UG_PET_DISMISS_PET_REQ,								// 펫의 소환 취소 요청

	UG_TRADE_START_REQ,									// 해당 유저와의 교환 요청
	UG_TRADE_OK_RES,									// 해당 유져의 응답
	UG_TRADE_ADD_REQ,                                   // 교환창에 아이템 등록
	UG_TRADE_DEL_REQ,									// 교환창에 아이템 삭제
	UG_TRADE_MODIFY_REQ,                                   // 교환창에 등록된 아이템 개수 변경
	UG_TRADE_ZENNY_UPDATE_REQ,							// 교환창에 제니 등록 및 변경
	UG_TRADE_END_REQ,									// 교환 완료 버튼 클릭
	UG_TRADE_CANCEL_REQ,								// 교환 취소 혹은 캐릭종료 거리 이탈시 사용
	UG_TRADE_DENY_REQ,									// 교환이 불가능 하게 하거나 가능하도록 한다.

	UG_GUILD_CREATE_REQ,								// 길드 만들기 ( Guild Creation/Disbanding )
	UG_GUILD_INVITE_REQ,								// 길드에 초대하기 ( Guild Member Invitation/Leaving/Kicking Out )

	UG_TUTORIAL_HINT_UPDATE_REQ,						// 힌트 진행 상황을 업데이트한다.
	UG_TUTORIAL_WAIT_CANCEL_REQ,						// 튜토리얼 대기 취소하기
	UG_TUTORIAL_PLAY_QUIT_REQ,							// 튜토리얼 플레이 취소하기

	UG_TIMEQUEST_ROOM_LIST_REQ,							// 타임머신 퀘스트 방 목록 요청
	UG_TIMEQUEST_ROOM_INFO_REQ,							// 타임머신 퀘스트 방 정보 요청
	UG_TIMEQUEST_ROOM_JOIN_REQ,							// 타임머신 퀘스트 방 진입 요청
	UG_TIMEQUEST_ROOM_LEAVE_REQ,						// 타임머신 퀘스트 방 퇴장 요청
	UG_TIMEQUEST_ROOM_TELEPORT_REQ,						// 타임머신 퀘스트 시작 위치로 텔레포트

	UG_RANKBATTLE_INFO_REQ,
	UG_RANKBATTLE_JOIN_REQ,
	UG_RANKBATTLE_LEAVE_REQ,

	UG_RANKBATTLE_ROOM_LIST_REQ,						// RankBattle 방 목록 요청
	UG_RANKBATTLE_ROOM_INFO_REQ,						// RankBattle 방 정보 요청
	UG_RANKBATTLE_ROOM_CREATE_REQ,						// RankBattle 방 생성 요청
	UG_RANKBATTLE_ROOM_LEAVE_REQ,						// RankBattle 방 삭제 요청
	UG_RANKBATTLE_ROOM_CHALLENGE_REQ,					// RankBattle 대련 요청
	UG_RANKBATTLE_ROOM_MATCH_CANCEL_REQ,				// RankBattle 대련 준비 완료 알림이 온 후 대련을 취소함(개인)

	UG_DRAGONBALL_CHECK_REQ,							// 드래곤볼 UI 7개 배치OK
	UG_DRAGONBALL_REWARD_REQ,							// 드래곤볼 다 모음에 대한 보상 선택 요청

	UG_PRIVATESHOP_CREATE_REQ,							// 상점을 만들어라 요청[6/28/2007 SGpro]
	UG_PRIVATESHOP_EXIT_REQ,							// 상점을 완전히 닫아라 요청[6/28/2007 SGpro]
	UG_PRIVATESHOP_OPEN_REQ,							// 상점 상태를 Open으로 해라 요청[6/28/2007 SGpro]
	UG_PRIVATESHOP_CLOSE_REQ,							// 상점 상태를 Close로 해라 요청[6/28/2007 SGpro]
	UG_PRIVATESHOP_ITEM_UPDATE_REQ,						// 상점 아이템에 내용을 변경 요청[6/29/2007 SGpro]
	UG_PRIVATESHOP_ITEM_INSERT_REQ,						// 상점 아이템 추가 요청[6/29/2007 SGpro]
	UG_PRIVATESHOP_ITEM_GET_REQ,						// 상점 아이템 정보 요청
	UG_PRIVATESHOP_ITEM_DELETE_REQ,						// 상점 아이템 삭제 요청[6/29/2007 SGpro]
	UG_PRIVATESHOP_ITEM_BUYING_REQ,						// 상점 아이템 사기 요청[6/29/2007 SGpro]
	UG_PRIVATESHOP_ENTER_REQ,							// 손님 입장[6/29/2007 SGpro]
	UG_PRIVATESHOP_LEAVE_REQ,							// 손님 퇴장[6/29/2007 SGpro]
	UG_PRIVATESHOP_ITEM_SELECT_REQ,						// 아이템 찜[7/19/2007 SGpro]

	UG_MAIL_START_REQ,
	UG_MAIL_SEND_REQ,
	UG_MAIL_READ_REQ,
	UG_MAIL_DEL_REQ,
	UG_MAIL_RETURN_REQ,
	UG_MAIL_RELOAD_REQ,
	UG_MAIL_LOAD_REQ,
	UG_MAIL_ITEM_RECEIVE_REQ,
	UG_MAIL_LOCK_REQ,
	UG_MAIL_MULTI_DEL_REQ,

	UG_PRIVATESHOP_BUSINESS_REQUEST_REQ,				// [10/17/2007 SGpro]
	UG_PRIVATESHOP_BUSINESS_CONSENT_RES,				// [10/17/2007 SGpro]
	UG_PRIVATESHOP_BUSINESS_WAITTIMEOUT_NFY,			// [10/17/2007 SGpro]
	UG_PRIVATESHOP_BUSINESS_PRICEFLUCTUATIONS_REQ,		// [10/17/2007 SGpro]
	UG_PRIVATESHOP_BUSINESS_IMMEDIATE_ITEM_BUYING_REQ,	// [10/17/2007 SGpro]
	UG_PRIVATESHOP_BUSINESS_CANCEL_REQ,					// [10/17/2007 SGpro]

	UG_PORTAL_START_REQ,
	UG_PORTAL_ADD_REQ,
	UG_PORTAL_REQ,

	UG_WAR_FOG_UPDATE_REQ,
	UG_GUILD_FUNCTION_ADD_REQ,
	UG_GUILD_GIVE_ZENNY,

	UG_GUILD_BANK_START_REQ,							// GUILD Warehouse 아이템 로딩
	UG_GUILD_BANK_MOVE_REQ,								// GUILD Warehouse 의 아이템 이동
	UG_GUILD_BANK_MOVE_STACK_REQ,						// GUILD Warehouse 의 스택아이템 이동
	UG_GUILD_BANK_END_REQ,								// GUILD Warehouse 를 닫는다.
	UG_GUILD_BANK_ZENNY_REQ,							// GUILD Warehouse 에 저금 혹은 인출한다.
	UG_GUILD_CREATE_MARK_REQ,							// GuildMark Create
	UG_GUILD_CHANGE_MARK_REQ,							// GuildMark Change

	UG_CROSSFIRE_REQ,
	UG_BANK_LOAD_REQ,

	UG_GUILD_CHANGE_NAME_REQ,

	UG_PARTY_SHARETARGET_REQ,							// [3/28/2008 SGpro]
	UG_RIDE_ON_BUS_REQ,
	UG_RIDE_OFF_BUS_REQ,

	UG_TRANSFORM_CANCEL_REQ,							// 변신 취소 요청
	UG_SHOP_ITEM_IDENTIFY_REQ,

	UG_DICE_ROLL_REQ,									// Action Skill 주사위 굴리기

	UG_BUDOKAI_JOIN_INDIVIDUAL_REQ,						// 개인 등록
	UG_BUDOKAI_LEAVE_INDIVIDUAL_REQ,					// 개인 취소

	UG_BUDOKAI_JOIN_TEAM_INFO_REQ,						//
	UG_BUDOKAI_JOIN_TEAM_REQ,							// 팀 등록
	UG_BUDOKAI_LEAVE_TEAM_REQ,							// 팀 취소
	UG_BUDOKAI_LEAVE_TEAM_MEMBER_REQ,					// 팀 멤버 취소

	UG_BUDOKAI_JOIN_INFO_REQ,							// 참가 정보 요청
	UG_BUDOKAI_JOIN_STATE_REQ,							// 참가 상태 요청
	UG_BUDOKAI_MUDOSA_INFO_REQ,							// 무도사 정보 요청
	UG_BUDOKAI_MUDOSA_TELEPORT_REQ,						// 무도사로 텔레포트 요청
	UG_BUDOKAI_PARTY_MAKER_REQ,							// 파티 생성 요청, 천하제일무도회 테스트용
	UG_BUDOKAI_SOCIAL_ACTION,
	UG_BUDOKAI_PRIZEWINNER_NAME_REQ,					// 우승자 / 준우승자 : 개인전
	//	UG_BUDOKAI_PRIZEWINNER_TEAM_NAME_REQ,				// 우승자 / 준우승자 : 팀전

	UG_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_REQ,				// 천하제일무도회 서버로 텔레포트 요청
	UG_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_REQ,				// 천하제일무도회 서버에서 원래 서버로 이동
	UG_BUDOKAI_GM_MATCH_PROGRESS_INFO_REQ,				// 경기 진행 정보 요청
	UG_BUDOKAI_GM_MATCH_ARENA_ENTER_REQ,				// 경기장 들어가기
	UG_BUDOKAI_GM_MATCH_ARENA_LEAVE_REQ,				// 경기장 나가기

	UG_SCOUTER_TURN_ON,									// 스카우터 상태 온
	UG_SCOUTER_TURN_OFF,								// 스카우터 상태 오프
	UG_SCOUTER_ITEM_SELL_REQ,							// 스카우터를 통한 아이템 팔기

	UG_SHOP_EVENTITEM_START_REQ,						// [7/15/2008 SGpro]
	UG_SHOP_EVENTITEM_BUY_REQ,							// [7/11/2008 SGpro]
	UG_SHOP_EVENTITEM_END_REQ,							// [7/15/2008 SGpro]

	UG_SHOP_GAMBLE_BUY_REQ,							// [7/11/2008 SGpro]

	UG_PARTY_DIFF_CHANGE_REQ,							// party dungeon diff change
	UG_PARTY_DUNGEON_INIT_REQ,							// party dungeon Init

	UG_SKILL_INIT_REQ,

	UG_PARTY_CHARM_DICE_ROLL_REQ,							// 파티참 등록 시 주사위 굴리기
	UG_PARTY_INVEN_LOCK_REQ,
	UG_PARTY_INVEN_RESET_REQ,
	UG_PARTY_INVEN_ACCEPTED_REQ,
	UG_PARTY_INVEN_GIVE_REQ,
	UG_PARTY_INVEN_DICE_START_REQ,
	UG_PARTY_INVEN_DICE_ROLL_REQ,					// 아이템 분배시 주사위 굴리기

	UG_TELEPORT_CONFIRM_REQ,

	UG_HOIPOIMIX_ITEM_CHECK_REQ,					// 만들아이템 선택 (필요한 아이템 수량 체크)
	UG_HOIPOIMIX_ITEM_MAKE_REQ,						// 아이템 만들기
	UG_HOIPOIMIX_ITEM_MAKE_EP_REQ,					// 아이템 만들기 중 EP 넣기
	UG_HOIPOIMIX_ITEM_MACHINE_MAKE_REQ,				// 머신 만들기
	UG_HOIPOIMIX_ITEM_MACHINE_DEL_REQ,				// 머신 삭제
	UG_HOIPOIMIX_JOB_SET_REQ,						// 믹스 잡 세팅
	UG_HOIPOIMIX_JOB_RESET_REQ,						// 믹스 잡 리셋

	UG_VEHICLE_DIRECT_PLAY_CANCEL_NFY,
	UG_VEHICLE_ENGINE_START_REQ,					// 탈 것 시동 켠다.
	UG_VEHICLE_ENGINE_STOP_REQ,						// 탈 것 시동 끈다.
	UG_VEHICLE_END_REQ,								// 탈 것 사용 중지.
	UG_VEHICLE_STUNT_NFY,							// 스페이스 바 누름(탈것)
	UG_VEHICLE_FUEL_REMOVE_NFY,

	// 승객 관련 작업은 다음 마일스톤~ 2009.1.5 승원.
	UG_VEHICLE_PASSENGER_GETON_REQ,
	UG_VEHICLE_ASK_RES,
	UG_VEHICLE_PASSENGER_GETOFF_REQ,

	UG_DOJO_CREATE_REQ,
	UG_DOJO_DELETE_REQ,
	UG_DOJO_FUNCTION_ADD_REQ,
	UG_DOJO_BANK_HISTORY_REQ,
	UG_DOGI_CREATE_REQ,								// 도복생성
	UG_DOGI_CHANGE_REQ,								// 도복변경
	UG_GUILD_DOGI_CREATE_REQ,						// 유파도복생성
	UG_GUILD_DOGI_CHANGE_REQ,						// 유파도복변경
	UG_DOJO_SCRAMBLE_REQ,							// 도장쟁탈전 신청
	UG_DOJO_SCRAMBLE_RESPONSE_REQ,					// 도장쟁탈전 신청에 대한 응답

	UG_SHOP_NETPYITEM_START_REQ,
	UG_SHOP_NETPYITEM_BUY_REQ,
	UG_SHOP_NETPYITEM_END_REQ,

	UG_WORLD_MAP_STATUS,
	UG_DOJO_NPC_INFO_REQ,							// 도장NPC에게 정보요청

	UG_GAMEGUARD_AUTH_ANSWER_RES,
	UG_GAMEGUARD_HACK_INFO_NFY,

	UG_SKILL_CASTING_CANCELED_NFY,					// 스킬 캐스팅 취소 알림

	UG_PET_ATTACK_TARGET_NFY,						// 펫의 전투 참여

	UG_DURATION_ITEM_BUY_REQ,						// 상점에서 구매시
	UG_DURATION_RENEW_REQ,							// 기간제 아이템 기간만 갱신요청시

	UG_CASHITEM_START_REQ,
	UG_CASHITEM_END_REQ,
	UG_CASHITEM_MOVE_REQ,
	UG_CASHITEM_USE_REQ,
	UG_CASHITEM_HLSHOP_START_REQ,					// 캐시 상점 열때
	UG_CASHITEM_HLSHOP_END_REQ,
	UG_CASHITEM_BUY_REQ,							// 캐쉬 아이템 구매시

	UG_BUDOKAI_PRIZEWINNER_TEAM_NAME_REQ,				// 우승자 / 준우승자 : 팀전
	UG_GMT_UPDATE_REQ,

	UG_CHAR_LOC_AFTER_KNOCKDOWN_NFY,
	UG_CHAR_LOC_AFTER_SLIDING_NFY,
	UG_CHAR_LOC_AFTER_PUSH_NFY,*/

	UG_OPCODE_DUMMY,
	UG_OPCODE_END = UG_OPCODE_DUMMY - 1

};