#pragma once

//-----------------------------------------------------------------------------------
//		Purpose	: 
//-----------------------------------------------------------------------------------

enum TeleportType {

	TELEPORT_TYPE_DEFAULT,
	TELEPORT_TYPE_GAME_IN,
	TELEPORT_TYPE_GAME_OUT,
	TELEPORT_TYPE_TELEPOPO,
	TELEPORT_TYPE_SKILL,
	TELEPORT_TYPE_NPC_PORTAL,
	TELEPORT_TYPE_POPOSTONE,
	TELEPORT_TYPE_WORLD_MOVE,
	TELEPORT_TYPE_TMQ_WORLD_MOVE,
	TELEPORT_TYPE_TMQ_PORTAL,

	TELEPORT_TYPE_RANKBATTLE,
	TELEPORT_TYPE_TIMEQUEST,
	TELEPORT_TYPE_TUTORIAL,
	TELEPORT_TYPE_BUDOKAI,
	TELEPORT_TYPE_MATCH,
	TELEPORT_TYPE_MINORMATCH,
	TELEPORT_TYPE_MAJORMATCH,
	TELEPORT_TYPE_FINALMATCH,

	TELEPORT_TYPE_COMMAND,
	TELEPORT_TYPE_GM,
	TELEPORT_TYPE_DUNGEON,
	TELEPORT_TYPE_DOJO,

	TELEPORT_TYPE_COUNT,

	TELEPORT_TYPE_INVALID = 0xFFui8,

	TELEPORT_TYPE_FIRST = TELEPORT_TYPE_GAME_IN,
	TELEPORT_TYPE_LAST = TELEPORT_TYPE_DUNGEON,
};